version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/etc/php82/conf.d/local.ini
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - skylake_network
        ports:
            - 8877:80

    supervisor:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - skylake_network

    db:
        image: mysql:5.7
        container_name: skylake-db
        restart: unless-stopped
        ports:
            - "3377:3306"
        environment:
            MYSQL_DATABASE: skylake
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: skylake
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/mysqld.cnf:/etc/mysql/my.cnf
            - db_data:/var/lib/mysql/
        networks:
            - skylake_network

    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - 8878:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
        networks:
            - skylake_network

#    soketi:
#        image: 'quay.io/soketi/soketi:latest-16-alpine'
#        #    container_name: skylake-sockets
#        environment:
#            SOKETI_DEBUG: '1'
#            SOKETI_METRICS_SERVER_PORT: '9601'
#        ports:
#            - '${SOKETI_PORT:-6003}:6001'
#            - '${SOKETI_METRICS_SERVER_PORT:-9603}:9601'
    #     networks:
    #         - skylake_network

    meilisearch:
        image: "getmeili/meilisearch:v0.30"
        #        command: [ "-v" ]
        restart: unless-stopped
        ports:
            - 7703:7700
        volumes:
            - meilisearch_data:/data.ms
        networks:
            - skylake_network

    redis:
        image: redis:6.2.4
        ports:
            - "6388:6379"
        networks:
            - skylake_network

volumes:
    db_data:
    meilisearch_data:

networks:
    skylake_network:
        name: skylake_network
